### ISSUE TITLE
Criar lista de possíveis questões para fazer com o publico alvo do app

### ISSUE THREAD

**Issue by vinifsouza** [vinifsouza/ES2N_ANTA_2021_2#2]
* Já teve problema com conta de água? 
 * Como você controla sua conta?
 * Como um aplicativo poderia auxiliar?

**Comment by Wendell182** [comment]
- Você é o único(a) que cuida dos gastos de consumo em sua residência?
- Já utilizou ou utiliza algum app de controle financeiro?
- Têm o hábito de comparar os gastos de consumo com meses anteriores?
- Já procurou o serviço de água e esgoto para resolução de problemas?
- teve alguma dificuldade com o contato do serviço de água e esgoto?
