### ISSUE TITLE
Criar lista de requisitos não funcionais

### ISSUE THREAD

**Issue by vinifsouza** [vinifsouza/ES2N_ANTA_2021_2#3]

**Comment by fernandobonfimandrade** [comment]
Requisitos não funcionais

- Produto :
    - A Interface deverá ser amigável e interativa.
    - A aplicação não deverá demorar mais que 10 segundos para ser inicializado.
    - A leitura do hidrometro deve ser precisa e em m3.
    - A leitura do hidrometro não deve demorar mais que 3 segundos.
    - A aplicação não deve ocupar mais que 500mb de memoria no aparelho.
    - Algumas funcionalidades devem estar disponivel off-line.
    - O usuario precisa estar conectado a internet para realizar algumas 
        operações no sistema.
    - A aplicação não terá o uso da Internet como obrigatório.    
  
  
- Organizacionais  
    - A aplicação deverá rodar em aparelhos com sistema Android 
            a partir da versão Android 8.0 Oreo.
    - A aplicação deve usar a camera do aparelho para coletar a 
            leitura do hidrometro atraves da biblioteca OCR Tesseract.
    - A aplicação deve usar um sistema de banco de dados não relacional MongoDB e
        banco de dados sqlLite para persistencia dos dados no aparelho.
    - A Api de comunicação com o servidor deve seguir a arquitetura RESTful.
    - A aplicação deve fazer uso de funções nativas do aparelho, como:
        GPS, Camera, Armazenamento e conexão com a internet, para isso deve
        ser usada a linguagem typescript juntamente com o framework React Native
        depois compilada para javascript.
    - O back-end da aplicação deve ser modulatizado em microserviços 
        organizado em containers, contendo os seguintes modulos:
            Servidor python para analise de imagens.
            Servidor node para gerenciamento de usuario e funcionalidades diversas
                da aplicação.
            Servidor MongoBD para banco de dados.  
    

- Segurança
    - A aplicação deve prezar pelo sigilo de informações pessoais inseridas.
    - O sistema deverá respeitar a LGPD (Lei Geral de Proteção de Dados) 
        e solicitar permissão do cliente para manter os seus dados e 
        usar as funções no aparelho, como camera, armazenamento, 
        localização gps uso de dados móveis.
    - A comunicação entre aplicação e servidor deve conter autenticação JWT código em Base64 .

**Comment by fernandobonfimandrade** [comment]
ok done
